### ISSUE TITLE
문서 작성

### ISSUE THREAD

**Issue by seongbin9786** [seongbin9786/wanted-pre-onboarding-frontend#25]
## Tasks
- [x] 기능 목록 및 기능 요구사항 설명
- [x] 설계 설명
- [x] 배포 방식 설명
- [x] 각 코드 블럭 설명 (`JSDoc` 사용)

## 예상 소요 시간
- 1h
